// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package full_lab_cep

import (
	"full_cycle_cep/pkg/presentation/http"
	"full_cycle_cep/pkg/shared/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeHandlers() *http.Handlers {
	loggerManager := log.NewLoggerManager()
	handlers := http.ProvideHandlers(loggerManager)
	return handlers
}

// wire.go:

var superset = wire.NewSet(wire.Bind(new(log.LoggerManagerInterface), new(*log.LoggerManager)), log.NewLoggerManager, http.ProvideHandlers)
